# Generated by Django 5.2.6 on 2025-09-30 08:42

from django.db import migrations
from datetime import datetime, timedelta, time
from django.utils import timezone
import random


def gen_user_tasks(apps, schema_editor):
    User = apps.get_model("pscds", "User")
    Project = apps.get_model("pscds", "Project")
    ProjectUser = apps.get_model("pscds", "ProjectUser")
    Task = apps.get_model("pscds", "Task")
    TaskUser = apps.get_model("pscds", "TaskUser")

    # Delete all TaskUsers
    TaskUser.objects.all().delete()
    Task.objects.all().delete()

    # Create 10 task for project Tosi Grow holding
    project = Project.objects.get(name="Tosi Grow Holding")
    project_users = ProjectUser.objects.filter(project=project)
    for i in range(10):
        task = Task.objects.create(
            project=project,
            task_name=f"Tosi Grow holding - Task {i+1}",
            description=f"Description of task {i+1}",
            work_time=random.randint(1, 10),
            warning_time=random.randint(1, 10),
            assigned_by=random.randint(1, 10),
            status_id=random.randint(1, 3),
            relative_position=random.randint(1, 10),
            due_date=timezone.now() + timedelta(days=random.randint(1, 10)),
        )
        user_tasks = project_users[random.randint(0, len(project_users) - 1)]
        TaskUser.objects.create(task=task, user=user_tasks.user)

        


class Migration(migrations.Migration):

    dependencies = [
        ("pscds", "0003_auto_20250927_0910"),
    ]

    operations = [
        migrations.RunPython(gen_user_tasks),
    ]
