# Generated by Django 5.2.5 on 2025-10-31 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('document_title', models.CharField(blank=True, help_text='Snapshot of document title', max_length=255, null=True)),
                ('document_content', models.TextField(blank=True, help_text='Snapshot of document content at session creation', null=True)),
                ('title', models.CharField(blank=True, help_text='Session title (auto-generated or user-set)', max_length=255, null=True)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'document_training_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='chathistory',
            name='document_tr_user_id_5bb36b_idx',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='document_training.document'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='document_training.chatsession'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session', 'created_at'], name='document_tr_session_620575_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='document_tr_user_id_7f08ce_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='document_tr_session_4b015a_idx'),
        ),
    ]
