# Generated by Django 5.2.5 on 2025-11-02 15:35

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_training', '0003_enable_pgvector_and_add_chunks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of this chunk')),
                ('chunk_index', models.IntegerField(help_text='Order of this chunk in the document')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document_training.document')),
            ],
            options={
                'db_table': 'document_training_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='document_tr_documen_4c0fbe_idx')],
            },
        ),
    ]
