# Generated by Django 5.2.5 on 2025-10-20 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, help_text='Đã xóa', verbose_name='Đã xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'fashion_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, help_text='Đã xóa', verbose_name='Đã xóa')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Địa chỉ giao hàng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PROCESSING', 'Đang xử lý'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao hàng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('RETURNED', 'Đã hoàn trả')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('CREDIT_CARD', 'Thẻ tín dụng'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'ZaloPay'), ('VNPAY', 'VNPay')], default='COD', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền hàng')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phí vận chuyển')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền giảm giá')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Lý do hủy')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã vận đơn')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'fashion_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='fashion_ord_code_e1ed28_idx'), models.Index(fields=['customer_phone'], name='fashion_ord_custome_379c12_idx'), models.Index(fields=['status', '-created_at'], name='fashion_ord_status_6b6639_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, help_text='Đã xóa', verbose_name='Đã xóa')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('product_type', models.CharField(choices=[('T_SHIRT', 'Áo thun'), ('SHIRT', 'Áo sơ mi'), ('DRESS', 'Váy'), ('JEANS', 'Quần jean'), ('PANTS', 'Quần tây'), ('SHORTS', 'Quần short'), ('JACKET', 'Áo khoác'), ('SWEATER', 'Áo len'), ('HOODIE', 'Áo hoodie'), ('SKIRT', 'Chân váy'), ('SHOES', 'Giày'), ('ACCESSORIES', 'Phụ kiện')], max_length=20, verbose_name='Loại sản phẩm')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('FREE_SIZE', 'Free Size')], max_length=20, verbose_name='Kích cỡ')),
                ('color', models.CharField(choices=[('BLACK', 'Đen'), ('WHITE', 'Trắng'), ('GRAY', 'Xám'), ('RED', 'Đỏ'), ('BLUE', 'Xanh dương'), ('NAVY', 'Xanh navy'), ('GREEN', 'Xanh lá'), ('YELLOW', 'Vàng'), ('PINK', 'Hồng'), ('ORANGE', 'Cam'), ('PURPLE', 'Tím'), ('BROWN', 'Nâu'), ('BEIGE', 'Be'), ('MULTI', 'Nhiều màu')], max_length=20, verbose_name='Màu sắc')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Hình ảnh chính')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chất liệu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order_bot.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'fashion_products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('product_size', models.CharField(max_length=20, verbose_name='Kích cỡ')),
                ('product_color', models.CharField(max_length=20, verbose_name='Màu sắc')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_bot.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_bot.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'fashion_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='fashion_pro_categor_9f3ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'size', 'color'], name='fashion_pro_product_649b09_idx'),
        ),
    ]
